### ISSUE TITLE
Minecraft 1.16.5 Exit Save Crashing

### ISSUE THREAD

**Issue by yancypro** [lazyMods/baubles-interface#1]
Ever since loading the "Baubles Interface" mod to Minecraft 1.16.5, I've experienced crashing on the exit save function. Can this be fixed? I have attached my crash report for your review. Please let me know if you need anything else or if you discover a different reason.

Thanks!
Yancy
[crash-2021-10-27_09.09.39-client.txt](https://github.com/lazyMods/baubles-interface/files/7426866/crash-2021-10-27_09.09.39-client.txt)

**Comment by lazynessmind** [comment]
I couldnt reproduce this bug.
